<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Simple MVC Tutorial</title>
    <meta name="description" content="Simple MVC Blog">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    <link rel="stylesheet" href="public/style.css">
</head>
<body>
<div class="container">
    <nav class="indigo lighten-3">
        <div class="nav-wrapper">
            <a href="#" class="brand-logo">Eniams Dev</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="sass.html">Model</a></li>
                <li><a href="badges.html">View</a></li>
                <li><a href="collapsible.html">Controller</a></li>
            </ul>
        </div>
    </nav>
    <div>
        <h1 class="right-align ">Article Detail</h1>
    </div>
    <div class="col s12 m7">
        <h2 class="header">Title</h2>
        <div class="card horizontal">
            <div class="card-image">
                <img src="https://lorempixel.com/100/190/nature/6">
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <p>I am a very simple card. I am good at containing small bits of information.</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
    </div>
</div>

</body>

